In [30]:
import pandas as pd
import numpy as np
results=pd.read_excel('Analytics_Attachment.xlsx', sheetname=1)
start_date = results['Date'][0]

teams_divisions=pd.read_excel('Analytics_Attachment.xlsx', sheetname=0)
teams_divisions['team_id'] = np.array([i for i in range(30)])

results['Day Number']=((results['Date']-start_date)/np.timedelta64(1, 'D')).astype(int)
results = results.drop('Date', axis=1)

results = results.merge(teams_divisions, left_on='Home Team', right_on='Team_Name', how='left')
results=results.rename(columns = {'Division_id':'Home_Division_id', 'team_id':'Home_team_id','Conference_id':'Home_Conference_id'})
del results['Team_Name']
results = results.merge(teams_divisions, left_on='Away Team', right_on='Team_Name', how='left')
results=results.rename(columns = {'Division_id':'Away_Division_id', 'team_id':'Away_team_id','Conference_id':'Away_Conference_id'})
del results['Team_Name']

results.loc[results['Winner'] == 'Home','Winning_team_id'] = results['Home_team_id']
results.loc[results['Winner'] == 'Home','Losing_team_id'] = results['Away_team_id']
results.loc[results['Winner'] == 'Home','Margin'] = (results['Home Score'] - results['Away Score']).astype(int)
results.loc[results['Winner'] == 'Away','Winning_team_id'] = results['Away_team_id']
results.loc[results['Winner'] == 'Away','Losing_team_id'] = results['Home_team_id']
results.loc[results['Winner'] == 'Away','Margin'] = (results['Away Score'] - results['Home Score']).astype(int)

results=results.drop(['Home_team_id','Away_team_id','Home Team', 'Away Team','Home Score', 'Away Score', 'Winner', 'Home Team', 'Away Team'], axis=1)

results['Winning_team_id'] = results['Winning_team_id'].astype(int)
results['Losing_team_id'] = results['Losing_team_id'].astype(int)
results['Margin'] = results['Margin'].astype(int)


results.loc[results['Away_Conference_id']==results['Home_Conference_id'], 'Conference'] = results['Home_Conference_id']
results.loc[results['Home_Conference_id']!=results['Away_Conference_id'], 'Conference'] = None
results.loc[results['Home_Division_id']==results['Away_Division_id'], 'Division'] = results['Home_Division_id']
results.loc[results['Home_Division_id']!=results['Away_Division_id'], 'Division'] = None

results=results.drop(['Home_Conference_id','Home_Division_id','Away_Conference_id','Away_Division_id'], axis=1)

eastern_conference = [[0 for i in range(15)] for i in range(15)]
western_conference = [[0 for i in range(15)] for i in range(15)]
for i in range(results.shape[0]):
    if results.iloc[i]['Conference'] == 'East':
        eastern_conference[results.iloc[i]['Winning_team_id']][results.iloc[i]['Losing_team_id']] += 1
        eastern_conference[results.iloc[i]['Losing_team_id']][results.iloc[i]['Winning_team_id']] += 1
    if results.iloc[i]['Conference'] == 'East':
        western_conference[results.iloc[i]['Winning_team_id']-15][results.iloc[i]['Losing_team_id']-15] += 1
        western_conference[results.iloc[i]['Losing_team_id']-15][results.iloc[i]['Winning_team_id']-15] += 1
results

,Day Number,Winning_team_id,Losing_team_id,Margin,Conference,Division
0,0,6,2,29,East,None
1,0,18,19,9,West,Northwest
2,0,29,20,29,West,None
3,1,12,13,12,East,Southeast
4,1,8,25,9,None,None
5,1,0,1,5,East,Atlantic
6,1,4,7,18,East,None
7,1,11,9,11,East,None
8,1,27,16,4,West,None
9,1,15,28,5,West,None
10,1,17,3,6,None,None
11,1,24,23,19,West,Pacific
12,1,22,26,6,West,None
13,2,10,14,15,East,Southeast
14,2,5,0,6,East,None
15,2,29,24,8,West,None
16,2,21,18,8,West,None
17,3,6,4,3,East,None
18,3,1,8,9,East,None
19,3,7,13,26,East,None
20,3,17,23,3,West,None
21,3,11,12,6,East,Southeast
22,3,26,25,8,West,Southwest
23,3,19,22,7,West,None
24,3,20,28,8,West,None
25,4,10,3,32,East,None
26,4,0,11,6,East,None
27,4,2,27,7,None,None
28,4,6,13,6,East,None
29,4,5,8,17,East,Central
...,...,...,...,...,...,...
1200,166,7,27,13,None,None
1201,166,22,16,1,West,None
1202,167,8,3,9,East,None
1203,167,0,1,9,East,Atlantic
1204,167,12,6,3,East,None
1205,167,5,13,47,East,None
1206,167,9,11,10,East,None
1207,167,14,7,4,East,None
1208,167,18,29,1,West,None
1209,167,21,26,29,West,None
1210,167,19,20,6,West,None
1211,168,10,11,27,East,Southeast
1212,168,17,16,2,West,Northwest
1213,168,15,25,18,West,None
1214,168,22,28,12,West,None
1215,168,24,23,25,West,Pacific
1216,169,13,7,4,East,None
1217,169,4,6,15,East,None
1218,169,0,9,18,East,None
1219,169,2,3,1,East,Atlantic
1220,169,12,14,8,East,Southeast
1221,169,5,1,39,East,None
1222,169,25,27,7,West,Southwest
1223,169,26,16,5,West,None
1224,169,15,17,6,West,Northwest
1225,169,8,10,18,East,None
1226,169,19,29,4,West,None
1227,169,21,24,20,West,Pacific
1228,169,20,22,15,West,Pacific
1229,169,28,18,3,West,None

In [67]:
teams_divisions

                 Team_Name Division_id Conference_id  team_id
0           Boston Celtics    Atlantic          East        0
1            Brooklyn Nets    Atlantic          East        1
2          New York Knicks    Atlantic          East        2
3       Philadelphia 76ers    Atlantic          East        3
4          Toronto Raptors    Atlantic          East        4
5            Chicago Bulls     Central          East        5
6      Cleveland Cavaliers     Central          East        6
7          Detroit Pistons     Central          East        7
8           Indiana Pacers     Central          East        8
9          Milwaukee Bucks     Central          East        9
10           Atlanta Hawks   Southeast          East       10
11       Charlotte Hornets   Southeast          East       11
12              Miami Heat   Southeast          East       12
13           Orlando Magic   Southeast          East       13
14      Washington Wizards   Southeast          East       14
15          Denver Nuggets   Northwest          West       15
16  Minnesota Timberwolves   Northwest          West       16
17   Oklahoma City Thunder   Northwest          West       17
18  Portland Trail Blazers   Northwest          West       18
19               Utah Jazz   Northwest          West       19
20   Golden State Warriors     Pacific          West       20
21             LA Clippers     Pacific          West       21
22      Los Angeles Lakers     Pacific          West       22
23            Phoenix Suns     Pacific          West       23
24        Sacramento Kings     Pacific          West       24
25        Dallas Mavericks   Southwest          West       25
26         Houston Rockets   Southwest          West       26
27       Memphis Grizzlies   Southwest          West       27
28    New Orleans Pelicans   Southwest          West       28
29       San Antonio Spurs   Southwest          West       29

In [153]:
class Team(object):
    def __init__(self, num):
        self.team_id = num
        self.wins=0
        self.possible_wins = 82
        self.conf_wins = 0
        self.poss_conf_wins = 52
        self.winning_margin = 0
        self.elim_day = -1
        self.eliminated = False
    def lose_game(self, frame):
        self.possible_wins -= 1
        if frame['Conference']:
            self.possible_conference_wins -= 1
        if frame['Division']:
            self.possible_division_wins -= 1
    def win_game(self, frame):
        self.wins += 1
    def __lt__(self, other):
        if self.wins < other.wins:
            return True
        elif self.wins == other.wins:
            if self.conf_wins < other.conf_wins:
                return True
        return False
    
    def __gt__(self, other):
        return not self.__lt__(other)
    
    def __eq__(self, other):
        return self.team_id == other.team_id
    def __neq__(self, other):
        return not self.__eq__(other)

In [151]:
team1 = Team(1)
team2 = Team(2)
team3 = Team(3)

team1.wins = 30
team2.wins = 29
team3.wins = 30
team1.conf_wins = 3
team3.conf_wins = 3

arr = [team1, team2, team3]
arr = sorted(arr)
arr[1].team_id

1

In [55]:

eastern = [Team(i) for i in range(15)]
western = [Team(i+15) for i in range(15)]

western[0].team_id

15

In [61]:
east_final_standings = {}
west_final_standings = {}
for i in range(30):
    if i < 15:
        east_final_standings[i] = 0
    else:
        west_final_standings[i] = 0

for i in range(results.shape[0]):
    if results.iloc[i]['Winning_team_id'] < 15:
        east_final_standings[results.iloc[i]['Winning_team_id']] += 1
    else:
        west_final_standings[results.iloc[i]['Winning_team_id']] += 1

east_threshold = sorted(east_final_standings.values())[-8] # eighth best team, represents "threshold" for playoffs
west_threshold = sorted(west_final_standings.values())[-8]

In [158]:
elim = {}

eastern = [Team(i) for i in range(15)]
western = [Team(i+15) for i in range(15)]

for i in range(results.shape[0]):
    if results.iloc[i]['Winning_team_id'] < 15:
        eastern[results.iloc[i]['Winning_team_id']].wins += 1
        if results.iloc[i]['Conference']:
            eastern[results.iloc[i]['Winning_team_id']].conf_wins += 1
            eastern[results.iloc[i]['Losing_team_id']].poss_conf_wins -= 1
    else:
        western[results.iloc[i]['Winning_team_id']-15].wins += 1
        if results.iloc[i]['Conference']:
            western[results.iloc[i]['Winning_team_id']-15].conf_wins += 1
            western[results.iloc[i]['Losing_team_id']-15].poss_conf_wins -= 1
    
        
    if results.iloc[i]['Losing_team_id'] < 15:
        losing_team = eastern[results.iloc[i]['Losing_team_id']]
        losing_team.possible_wins -= 1
        east_eighth = sorted(eastern)[-8]
        if (losing_team.possible_wins < east_eighth.wins and not losing_team.eliminated):
            losing_team.eliminated = True
            losing_team.elim_day = results.iloc[i]['Day Number']
        elif (east_eighth.wins == losing_team.possible_wins):
            if (losing_team.poss_conf_wins < east_eighth.conf_wins and not losing_team.eliminated):
                losing_team.eliminated = True
                losing_team.elim_day = results.iloc[i]['Day Number']
    else:
        losing_team = western[results.iloc[i]['Losing_team_id']-15]
        losing_team.possible_wins -= 1
        west_eighth = sorted(western)[-8]
        if (losing_team.possible_wins < west_eighth.wins and not losing_team.eliminated):
            losing_team.eliminated = True
            losing_team.elim_day = results.iloc[i]['Day Number'] 
        elif (west_eighth.wins == losing_team.possible_wins):
            if (losing_team.poss_conf_wins < west_eighth.conf_wins and not losing_team.eliminated):
                losing_team.eliminated = True
                losing_team.elim_day = results.iloc[i]['Day Number']
                
east_eighth = sorted(eastern)[-8]
print east_eighth.team_id
for team in eastern:
    if team != east_eighth:
        if (team.possible_wins < east_eighth.wins and not team.eliminated):
            team.eliminated = True
            team.elim_day = results.iloc[-1]['Day Number']
        elif (east_eighth.wins == team.possible_wins):
            print team.team_id
            if (team.poss_conf_wins < east_eighth.conf_wins and not team.eliminated):
                team.eliminated = True
                team.elim_day = results.iloc[-1]['Day Number']
                
west_eighth = sorted(western)[-8]
print west_eighth.team_id
for team in western:
    if team != west_eighth:
        if (team.possible_wins < west_eighth.wins and not team.eliminated):
            team.eliminated = True
            team.elim_day = results.iloc[-1]['Day Number']
        elif (west_eighth.wins == team.possible_wins):
            print team.team_id
            if (team.poss_conf_wins < west_eighth.conf_wins and not team.eliminated):
                team.eliminated = True
                team.elim_day = results.iloc[-1]['Day Number']

5
12
18

In [ ]:
pull_conference_eigth()

In [159]:
r = [0 for i in range(30)]
for team in eastern:
    r[team.team_id] = team.elim_day

for team in western:
    r[team.team_id] = team.elim_day
elim = pd.DataFrame(r, columns=["elim"])
elim['team_id'] = np.array([i for i in range(30)])
elim = elim.merge(teams_divisions, on='team_id', how='left')
elim.loc[elim['elim']!=-1, 'Date Eliminated'] = (start_date + pd.to_timedelta(elim['elim'], unit='D')).dt.strftime("%m/%d/%Y").astype(str)
elim.loc[elim['elim']==-1, 'Date Eliminated'] = "Playoffs"
elim = elim.sort_values(by=['Team_Name']).drop(['team_id','Division_id','Conference_id'], 
                                               axis=1).rename({'Team_name':"Team"})
elim

    elim               Team_Name Date Eliminated
10    -1           Atlanta Hawks        Playoffs
0     -1          Boston Celtics        Playoffs
1    134           Brooklyn Nets      03/08/2017
11   165       Charlotte Hornets      04/08/2017
5     -1           Chicago Bulls        Playoffs
6     -1     Cleveland Cavaliers        Playoffs
25   161        Dallas Mavericks      04/04/2017
15   166          Denver Nuggets      04/09/2017
7    167         Detroit Pistons      04/10/2017
20    -1   Golden State Warriors        Playoffs
26    -1         Houston Rockets        Playoffs
8     -1          Indiana Pacers        Playoffs
21    -1             LA Clippers        Playoffs
22   145      Los Angeles Lakers      03/19/2017
27    -1       Memphis Grizzlies        Playoffs
12   169              Miami Heat      04/12/2017
9     -1         Milwaukee Bucks        Playoffs
16   161  Minnesota Timberwolves      04/04/2017
28   159    New Orleans Pelicans      04/02/2017
2    155         New York Knicks      03/29/2017
17    -1   Oklahoma City Thunder        Playoffs
13   155           Orlando Magic      03/29/2017
3    155      Philadelphia 76ers      03/29/2017
23   147            Phoenix Suns      03/21/2017
18    -1  Portland Trail Blazers        Playoffs
24   157        Sacramento Kings      03/31/2017
29    -1       San Antonio Spurs        Playoffs
4     -1         Toronto Raptors        Playoffs
19    -1               Utah Jazz        Playoffs
14    -1      Washington Wizards        Playoffs

In [160]:
elim.to_csv()

',elim,Team_Name,Date Eliminated\n10,-1,Atlanta Hawks,Playoffs\n0,-1,Boston Celtics,Playoffs\n1,134,Brooklyn Nets,03/08/2017\n11,165,Charlotte Hornets,04/08/2017\n5,-1,Chicago Bulls,Playoffs\n6,-1,Cleveland Cavaliers,Playoffs\n25,161,Dallas Mavericks,04/04/2017\n15,166,Denver Nuggets,04/09/2017\n7,167,Detroit Pistons,04/10/2017\n20,-1,Golden State Warriors,Playoffs\n26,-1,Houston Rockets,Playoffs\n8,-1,Indiana Pacers,Playoffs\n21,-1,LA Clippers,Playoffs\n22,145,Los Angeles Lakers,03/19/2017\n27,-1,Memphis Grizzlies,Playoffs\n12,169,Miami Heat,04/12/2017\n9,-1,Milwaukee Bucks,Playoffs\n16,161,Minnesota Timberwolves,04/04/2017\n28,159,New Orleans Pelicans,04/02/2017\n2,155,New York Knicks,03/29/2017\n17,-1,Oklahoma City Thunder,Playoffs\n13,155,Orlando Magic,03/29/2017\n3,155,Philadelphia 76ers,03/29/2017\n23,147,Phoenix Suns,03/21/2017\n18,-1,Portland Trail Blazers,Playoffs\n24,157,Sacramento Kings,03/31/2017\n29,-1,San Antonio Spurs,Playoffs\n4,-1,Toronto Raptors,Playoffs\n19,-1,Utah Jazz,Playoffs\n14,-1,Washington Wizards,Playoffs\n'